<?php

/* REDIS */
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_REDIS_ENABLED', true);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_REDIS_HOST', '127.0.0.1');
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_REDIS_PORT', 6379);

