<?php

/* REDIS */
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_REDIS_ENABLED', true);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_REDIS_HOST', '127.0.0.1');
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_REDIS_PORT', 6379);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_REDIS_COLLECTION', 'test');

/* MONGO */
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_MONGO_ENABLED', true);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_MONGO_HOST', '127.0.0.1');
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_MONGO_PORT', 27017);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_MONGO_DATABASE', 'dbtest');
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_MONGO_COLLECTION', 'test');

/* COUCH */
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_COUCH_ENABLED', true);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_COUCH_HOST', '127.0.0.1');
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_COUCH_PORT', 5984);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_COUCH_DATABASE', 'dbtest');
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_COUCH_COLLECTION', 'test');


/* RIAK */
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_RIAK_ENABLED', true);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_RIAK_HOST', '127.0.0.1');
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_RIAK_PORT', 8098);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_RIAK_COLLECTION', 'test');

/* VOLDEMORT */
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_VOLDEMORT_ENABLED', false);
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_VOLDEMORT_HOST', '127.0.0.1');
define('TESTS_ZEND_DB_DOCUMENT_ADAPTER_VOLDEMORT_PORT', 6666);

